name: Server Test

on:
  workflow_call:
    inputs:
      server_type:
        required: true
        type: string
      server_image:
        required: true
        type: string
jobs:
  server_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Checkout CI runner
        uses: actions/checkout@v4
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'

      - name: Run tests
        env:
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
          PRICE: ${{ secrets.TEST_PRICE }}
        run: |
          source sample-ci/helpers.sh
          setup_dependencies

          install_docker_compose_settings
          export STRIPE_WEBHOOK_SECRET=$(retrieve_webhook_secret)
          cat <<EOF >> .env
          DOMAIN=http://web:4242
          PRICE=${PRICE}
          PAYMENT_METHOD_TYPES="card,ideal"
          EOF

          configure_docker_compose_for_integration . "${{ inputs.server_type }}" ../../client/html "${{ inputs.server_image }}"

          docker compose up -d && wait_web_server
          docker compose exec -T runner bundle exec rspec spec/client_and_server_spec.rb

      - name: Collect debug information
        if: ${{ failure() }}
        run: |
          cat .env
          cat docker-compose.yml
          docker compose ps -a
          docker compose logs web